log_level: debug
api:
  enabled: true
  host: localhost
  port: :8080
job:
  enabled: true
  workers: 1
ffmpeg:
  ## Run `make ffmpeg` to get ffmpeg binary
  path: ./bin/ffmpeg/ffmpeg
kafka:
  enabled: true
  producer:
    brokers:
      - localhost:9092
    topic: "event"
  consumer:
    brokers:
      - localhost:9092
    group_id: "video-editor-job-consumer"
    topic: "event"
    offset: "latest"
