apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.applicationName }}-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/{{ .Values.pvName }}
