apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.applicationName }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: {{ .Values.applicationName }}-pv